[general]
import = [
  "~/.config/alacritty/theme.toml"
]

[font]
normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font", style = "Bold" }
size = 13.0
